#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSysteMc.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BL")]
	public partial class BSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 擴充性方法定義
    partial void OnCreated();
    partial void InsertNHI_med(NHI_med instance);
    partial void UpdateNHI_med(NHI_med instance);
    partial void DeleteNHI_med(NHI_med instance);
    partial void InsertNHI_hosp(NHI_hosp instance);
    partial void UpdateNHI_hosp(NHI_hosp instance);
    partial void DeleteNHI_hosp(NHI_hosp instance);
    #endregion
		
		public BSDataContext() : 
				base(global::ClinicSysteMc.Properties.Settings.Default.BLConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<NHI_med> NHI_med
		{
			get
			{
				return this.GetTable<NHI_med>();
			}
		}
		
		public System.Data.Linq.Table<NHI_hosp> NHI_hosp
		{
			get
			{
				return this.GetTable<NHI_hosp>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHI_med")]
	public partial class NHI_med : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _NewMark;
		
		private string _OralMed;
		
		private string _Complex;
		
		private string _NHI_code;
		
		private string _NHI_price;
		
		private string _begin_date;
		
		private string _end_date;
		
		private string _ename;
		
		private string _spec_dose;
		
		private string _spec_unit;
		
		private string _comp_name;
		
		private string _comp_dose;
		
		private string _comp_unit;
		
		private string _prep;
		
		private string _vendor;
		
		private string _clas;
		
		private string _quality;
		
		private string _cname;
		
		private string _group_name;
		
		private string _comp1;
		
		private string _comp1_dose;
		
		private string _comp1_unit;
		
		private string _comp2;
		
		private string _comp2_dose;
		
		private string _comp2_unit;
		
		private string _comp3;
		
		private string _comp3_dose;
		
		private string _comp3_unit;
		
		private string _comp4;
		
		private string _comp4_dose;
		
		private string _comp4_unit;
		
		private string _comp5;
		
		private string _comp5_dose;
		
		private string _comp5_unit;
		
		private string _manufacturer;
		
		private string _ATC_code;
		
		private string _NoProduce;
		
		private System.DateTime _QDATE;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNewMarkChanging(string value);
    partial void OnNewMarkChanged();
    partial void OnOralMedChanging(string value);
    partial void OnOralMedChanged();
    partial void OnComplexChanging(string value);
    partial void OnComplexChanged();
    partial void OnNHI_codeChanging(string value);
    partial void OnNHI_codeChanged();
    partial void OnNHI_priceChanging(string value);
    partial void OnNHI_priceChanged();
    partial void Onbegin_dateChanging(string value);
    partial void Onbegin_dateChanged();
    partial void Onend_dateChanging(string value);
    partial void Onend_dateChanged();
    partial void OnenameChanging(string value);
    partial void OnenameChanged();
    partial void Onspec_doseChanging(string value);
    partial void Onspec_doseChanged();
    partial void Onspec_unitChanging(string value);
    partial void Onspec_unitChanged();
    partial void Oncomp_nameChanging(string value);
    partial void Oncomp_nameChanged();
    partial void Oncomp_doseChanging(string value);
    partial void Oncomp_doseChanged();
    partial void Oncomp_unitChanging(string value);
    partial void Oncomp_unitChanged();
    partial void OnprepChanging(string value);
    partial void OnprepChanged();
    partial void OnvendorChanging(string value);
    partial void OnvendorChanged();
    partial void OnclasChanging(string value);
    partial void OnclasChanged();
    partial void OnqualityChanging(string value);
    partial void OnqualityChanged();
    partial void OncnameChanging(string value);
    partial void OncnameChanged();
    partial void Ongroup_nameChanging(string value);
    partial void Ongroup_nameChanged();
    partial void Oncomp1Changing(string value);
    partial void Oncomp1Changed();
    partial void Oncomp1_doseChanging(string value);
    partial void Oncomp1_doseChanged();
    partial void Oncomp1_unitChanging(string value);
    partial void Oncomp1_unitChanged();
    partial void Oncomp2Changing(string value);
    partial void Oncomp2Changed();
    partial void Oncomp2_doseChanging(string value);
    partial void Oncomp2_doseChanged();
    partial void Oncomp2_unitChanging(string value);
    partial void Oncomp2_unitChanged();
    partial void Oncomp3Changing(string value);
    partial void Oncomp3Changed();
    partial void Oncomp3_doseChanging(string value);
    partial void Oncomp3_doseChanged();
    partial void Oncomp3_unitChanging(string value);
    partial void Oncomp3_unitChanged();
    partial void Oncomp4Changing(string value);
    partial void Oncomp4Changed();
    partial void Oncomp4_doseChanging(string value);
    partial void Oncomp4_doseChanged();
    partial void Oncomp4_unitChanging(string value);
    partial void Oncomp4_unitChanged();
    partial void Oncomp5Changing(string value);
    partial void Oncomp5Changed();
    partial void Oncomp5_doseChanging(string value);
    partial void Oncomp5_doseChanged();
    partial void Oncomp5_unitChanging(string value);
    partial void Oncomp5_unitChanged();
    partial void OnmanufacturerChanging(string value);
    partial void OnmanufacturerChanged();
    partial void OnATC_codeChanging(string value);
    partial void OnATC_codeChanged();
    partial void OnNoProduceChanging(string value);
    partial void OnNoProduceChanged();
    partial void OnQDATEChanging(System.DateTime value);
    partial void OnQDATEChanged();
    #endregion
		
		public NHI_med()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewMark", DbType="VarChar(2)")]
		public string NewMark
		{
			get
			{
				return this._NewMark;
			}
			set
			{
				if ((this._NewMark != value))
				{
					this.OnNewMarkChanging(value);
					this.SendPropertyChanging();
					this._NewMark = value;
					this.SendPropertyChanged("NewMark");
					this.OnNewMarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OralMed", DbType="VarChar(10)")]
		public string OralMed
		{
			get
			{
				return this._OralMed;
			}
			set
			{
				if ((this._OralMed != value))
				{
					this.OnOralMedChanging(value);
					this.SendPropertyChanging();
					this._OralMed = value;
					this.SendPropertyChanged("OralMed");
					this.OnOralMedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Complex", DbType="VarChar(2)")]
		public string Complex
		{
			get
			{
				return this._Complex;
			}
			set
			{
				if ((this._Complex != value))
				{
					this.OnComplexChanging(value);
					this.SendPropertyChanging();
					this._Complex = value;
					this.SendPropertyChanged("Complex");
					this.OnComplexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NHI_code", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string NHI_code
		{
			get
			{
				return this._NHI_code;
			}
			set
			{
				if ((this._NHI_code != value))
				{
					this.OnNHI_codeChanging(value);
					this.SendPropertyChanging();
					this._NHI_code = value;
					this.SendPropertyChanged("NHI_code");
					this.OnNHI_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NHI_price", DbType="VarChar(9)")]
		public string NHI_price
		{
			get
			{
				return this._NHI_price;
			}
			set
			{
				if ((this._NHI_price != value))
				{
					this.OnNHI_priceChanging(value);
					this.SendPropertyChanging();
					this._NHI_price = value;
					this.SendPropertyChanged("NHI_price");
					this.OnNHI_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_begin_date", DbType="VarChar(7) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string begin_date
		{
			get
			{
				return this._begin_date;
			}
			set
			{
				if ((this._begin_date != value))
				{
					this.Onbegin_dateChanging(value);
					this.SendPropertyChanging();
					this._begin_date = value;
					this.SendPropertyChanged("begin_date");
					this.Onbegin_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_end_date", DbType="VarChar(7)")]
		public string end_date
		{
			get
			{
				return this._end_date;
			}
			set
			{
				if ((this._end_date != value))
				{
					this.Onend_dateChanging(value);
					this.SendPropertyChanging();
					this._end_date = value;
					this.SendPropertyChanged("end_date");
					this.Onend_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ename", DbType="VarChar(120)")]
		public string ename
		{
			get
			{
				return this._ename;
			}
			set
			{
				if ((this._ename != value))
				{
					this.OnenameChanging(value);
					this.SendPropertyChanging();
					this._ename = value;
					this.SendPropertyChanged("ename");
					this.OnenameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_spec_dose", DbType="VarChar(7)")]
		public string spec_dose
		{
			get
			{
				return this._spec_dose;
			}
			set
			{
				if ((this._spec_dose != value))
				{
					this.Onspec_doseChanging(value);
					this.SendPropertyChanging();
					this._spec_dose = value;
					this.SendPropertyChanged("spec_dose");
					this.Onspec_doseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_spec_unit", DbType="VarChar(52)")]
		public string spec_unit
		{
			get
			{
				return this._spec_unit;
			}
			set
			{
				if ((this._spec_unit != value))
				{
					this.Onspec_unitChanging(value);
					this.SendPropertyChanging();
					this._spec_unit = value;
					this.SendPropertyChanged("spec_unit");
					this.Onspec_unitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comp_name", DbType="VarChar(56)")]
		public string comp_name
		{
			get
			{
				return this._comp_name;
			}
			set
			{
				if ((this._comp_name != value))
				{
					this.Oncomp_nameChanging(value);
					this.SendPropertyChanging();
					this._comp_name = value;
					this.SendPropertyChanged("comp_name");
					this.Oncomp_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comp_dose", DbType="VarChar(12)")]
		public string comp_dose
		{
			get
			{
				return this._comp_dose;
			}
			set
			{
				if ((this._comp_dose != value))
				{
					this.Oncomp_doseChanging(value);
					this.SendPropertyChanging();
					this._comp_dose = value;
					this.SendPropertyChanged("comp_dose");
					this.Oncomp_doseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comp_unit", DbType="VarChar(51)")]
		public string comp_unit
		{
			get
			{
				return this._comp_unit;
			}
			set
			{
				if ((this._comp_unit != value))
				{
					this.Oncomp_unitChanging(value);
					this.SendPropertyChanging();
					this._comp_unit = value;
					this.SendPropertyChanged("comp_unit");
					this.Oncomp_unitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prep", DbType="VarChar(86)")]
		public string prep
		{
			get
			{
				return this._prep;
			}
			set
			{
				if ((this._prep != value))
				{
					this.OnprepChanging(value);
					this.SendPropertyChanging();
					this._prep = value;
					this.SendPropertyChanged("prep");
					this.OnprepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vendor", DbType="VarChar(20)")]
		public string vendor
		{
			get
			{
				return this._vendor;
			}
			set
			{
				if ((this._vendor != value))
				{
					this.OnvendorChanging(value);
					this.SendPropertyChanging();
					this._vendor = value;
					this.SendPropertyChanged("vendor");
					this.OnvendorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clas", DbType="VarChar(1)")]
		public string clas
		{
			get
			{
				return this._clas;
			}
			set
			{
				if ((this._clas != value))
				{
					this.OnclasChanging(value);
					this.SendPropertyChanging();
					this._clas = value;
					this.SendPropertyChanged("clas");
					this.OnclasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quality", DbType="VarChar(1)")]
		public string quality
		{
			get
			{
				return this._quality;
			}
			set
			{
				if ((this._quality != value))
				{
					this.OnqualityChanging(value);
					this.SendPropertyChanging();
					this._quality = value;
					this.SendPropertyChanged("quality");
					this.OnqualityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cname", DbType="VarChar(128)")]
		public string cname
		{
			get
			{
				return this._cname;
			}
			set
			{
				if ((this._cname != value))
				{
					this.OncnameChanging(value);
					this.SendPropertyChanging();
					this._cname = value;
					this.SendPropertyChanged("cname");
					this.OncnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_group_name", DbType="VarChar(300)")]
		public string group_name
		{
			get
			{
				return this._group_name;
			}
			set
			{
				if ((this._group_name != value))
				{
					this.Ongroup_nameChanging(value);
					this.SendPropertyChanging();
					this._group_name = value;
					this.SendPropertyChanged("group_name");
					this.Ongroup_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comp1", DbType="VarChar(56)")]
		public string comp1
		{
			get
			{
				return this._comp1;
			}
			set
			{
				if ((this._comp1 != value))
				{
					this.Oncomp1Changing(value);
					this.SendPropertyChanging();
					this._comp1 = value;
					this.SendPropertyChanged("comp1");
					this.Oncomp1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comp1_dose", DbType="VarChar(11)")]
		public string comp1_dose
		{
			get
			{
				return this._comp1_dose;
			}
			set
			{
				if ((this._comp1_dose != value))
				{
					this.Oncomp1_doseChanging(value);
					this.SendPropertyChanging();
					this._comp1_dose = value;
					this.SendPropertyChanged("comp1_dose");
					this.Oncomp1_doseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comp1_unit", DbType="VarChar(51)")]
		public string comp1_unit
		{
			get
			{
				return this._comp1_unit;
			}
			set
			{
				if ((this._comp1_unit != value))
				{
					this.Oncomp1_unitChanging(value);
					this.SendPropertyChanging();
					this._comp1_unit = value;
					this.SendPropertyChanged("comp1_unit");
					this.Oncomp1_unitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comp2", DbType="VarChar(56)")]
		public string comp2
		{
			get
			{
				return this._comp2;
			}
			set
			{
				if ((this._comp2 != value))
				{
					this.Oncomp2Changing(value);
					this.SendPropertyChanging();
					this._comp2 = value;
					this.SendPropertyChanged("comp2");
					this.Oncomp2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comp2_dose", DbType="VarChar(11)")]
		public string comp2_dose
		{
			get
			{
				return this._comp2_dose;
			}
			set
			{
				if ((this._comp2_dose != value))
				{
					this.Oncomp2_doseChanging(value);
					this.SendPropertyChanging();
					this._comp2_dose = value;
					this.SendPropertyChanged("comp2_dose");
					this.Oncomp2_doseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comp2_unit", DbType="VarChar(51)")]
		public string comp2_unit
		{
			get
			{
				return this._comp2_unit;
			}
			set
			{
				if ((this._comp2_unit != value))
				{
					this.Oncomp2_unitChanging(value);
					this.SendPropertyChanging();
					this._comp2_unit = value;
					this.SendPropertyChanged("comp2_unit");
					this.Oncomp2_unitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comp3", DbType="VarChar(56)")]
		public string comp3
		{
			get
			{
				return this._comp3;
			}
			set
			{
				if ((this._comp3 != value))
				{
					this.Oncomp3Changing(value);
					this.SendPropertyChanging();
					this._comp3 = value;
					this.SendPropertyChanged("comp3");
					this.Oncomp3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comp3_dose", DbType="VarChar(11)")]
		public string comp3_dose
		{
			get
			{
				return this._comp3_dose;
			}
			set
			{
				if ((this._comp3_dose != value))
				{
					this.Oncomp3_doseChanging(value);
					this.SendPropertyChanging();
					this._comp3_dose = value;
					this.SendPropertyChanged("comp3_dose");
					this.Oncomp3_doseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comp3_unit", DbType="VarChar(51)")]
		public string comp3_unit
		{
			get
			{
				return this._comp3_unit;
			}
			set
			{
				if ((this._comp3_unit != value))
				{
					this.Oncomp3_unitChanging(value);
					this.SendPropertyChanging();
					this._comp3_unit = value;
					this.SendPropertyChanged("comp3_unit");
					this.Oncomp3_unitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comp4", DbType="VarChar(56)")]
		public string comp4
		{
			get
			{
				return this._comp4;
			}
			set
			{
				if ((this._comp4 != value))
				{
					this.Oncomp4Changing(value);
					this.SendPropertyChanging();
					this._comp4 = value;
					this.SendPropertyChanged("comp4");
					this.Oncomp4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comp4_dose", DbType="VarChar(11)")]
		public string comp4_dose
		{
			get
			{
				return this._comp4_dose;
			}
			set
			{
				if ((this._comp4_dose != value))
				{
					this.Oncomp4_doseChanging(value);
					this.SendPropertyChanging();
					this._comp4_dose = value;
					this.SendPropertyChanged("comp4_dose");
					this.Oncomp4_doseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comp4_unit", DbType="VarChar(51)")]
		public string comp4_unit
		{
			get
			{
				return this._comp4_unit;
			}
			set
			{
				if ((this._comp4_unit != value))
				{
					this.Oncomp4_unitChanging(value);
					this.SendPropertyChanging();
					this._comp4_unit = value;
					this.SendPropertyChanged("comp4_unit");
					this.Oncomp4_unitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comp5", DbType="VarChar(56)")]
		public string comp5
		{
			get
			{
				return this._comp5;
			}
			set
			{
				if ((this._comp5 != value))
				{
					this.Oncomp5Changing(value);
					this.SendPropertyChanging();
					this._comp5 = value;
					this.SendPropertyChanged("comp5");
					this.Oncomp5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comp5_dose", DbType="VarChar(11)")]
		public string comp5_dose
		{
			get
			{
				return this._comp5_dose;
			}
			set
			{
				if ((this._comp5_dose != value))
				{
					this.Oncomp5_doseChanging(value);
					this.SendPropertyChanging();
					this._comp5_dose = value;
					this.SendPropertyChanged("comp5_dose");
					this.Oncomp5_doseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comp5_unit", DbType="VarChar(51)")]
		public string comp5_unit
		{
			get
			{
				return this._comp5_unit;
			}
			set
			{
				if ((this._comp5_unit != value))
				{
					this.Oncomp5_unitChanging(value);
					this.SendPropertyChanging();
					this._comp5_unit = value;
					this.SendPropertyChanged("comp5_unit");
					this.Oncomp5_unitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manufacturer", DbType="VarChar(42)")]
		public string manufacturer
		{
			get
			{
				return this._manufacturer;
			}
			set
			{
				if ((this._manufacturer != value))
				{
					this.OnmanufacturerChanging(value);
					this.SendPropertyChanging();
					this._manufacturer = value;
					this.SendPropertyChanged("manufacturer");
					this.OnmanufacturerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ATC_code", DbType="VarChar(8)")]
		public string ATC_code
		{
			get
			{
				return this._ATC_code;
			}
			set
			{
				if ((this._ATC_code != value))
				{
					this.OnATC_codeChanging(value);
					this.SendPropertyChanging();
					this._ATC_code = value;
					this.SendPropertyChanged("ATC_code");
					this.OnATC_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoProduce", DbType="VarChar(1)")]
		public string NoProduce
		{
			get
			{
				return this._NoProduce;
			}
			set
			{
				if ((this._NoProduce != value))
				{
					this.OnNoProduceChanging(value);
					this.SendPropertyChanging();
					this._NoProduce = value;
					this.SendPropertyChanged("NoProduce");
					this.OnNoProduceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QDATE", DbType="DateTime NOT NULL")]
		public System.DateTime QDATE
		{
			get
			{
				return this._QDATE;
			}
			set
			{
				if ((this._QDATE != value))
				{
					this.OnQDATEChanging(value);
					this.SendPropertyChanging();
					this._QDATE = value;
					this.SendPropertyChanged("QDATE");
					this.OnQDATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHI_hosp")]
	public partial class NHI_hosp : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private char _Div;
		
		private string _NHI_code;
		
		private string _Nam;
		
		private string _Adr;
		
		private string _Loc;
		
		private string _Tel;
		
		private char _Clas;
		
		private string _Form;
		
		private char _Typ;
		
		private string _end_date;
		
		private System.Nullable<char> _Stat;
		
		private System.DateTime _QDATE;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDivChanging(char value);
    partial void OnDivChanged();
    partial void OnNHI_codeChanging(string value);
    partial void OnNHI_codeChanged();
    partial void OnNamChanging(string value);
    partial void OnNamChanged();
    partial void OnAdrChanging(string value);
    partial void OnAdrChanged();
    partial void OnLocChanging(string value);
    partial void OnLocChanged();
    partial void OnTelChanging(string value);
    partial void OnTelChanged();
    partial void OnClasChanging(char value);
    partial void OnClasChanged();
    partial void OnFormChanging(string value);
    partial void OnFormChanged();
    partial void OnTypChanging(char value);
    partial void OnTypChanged();
    partial void Onend_dateChanging(string value);
    partial void Onend_dateChanged();
    partial void OnStatChanging(System.Nullable<char> value);
    partial void OnStatChanged();
    partial void OnQDATEChanging(System.DateTime value);
    partial void OnQDATEChanged();
    #endregion
		
		public NHI_hosp()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Div", DbType="Char(1) NOT NULL")]
		public char Div
		{
			get
			{
				return this._Div;
			}
			set
			{
				if ((this._Div != value))
				{
					this.OnDivChanging(value);
					this.SendPropertyChanging();
					this._Div = value;
					this.SendPropertyChanged("Div");
					this.OnDivChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NHI_code", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string NHI_code
		{
			get
			{
				return this._NHI_code;
			}
			set
			{
				if ((this._NHI_code != value))
				{
					this.OnNHI_codeChanging(value);
					this.SendPropertyChanging();
					this._NHI_code = value;
					this.SendPropertyChanged("NHI_code");
					this.OnNHI_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nam", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nam
		{
			get
			{
				return this._Nam;
			}
			set
			{
				if ((this._Nam != value))
				{
					this.OnNamChanging(value);
					this.SendPropertyChanging();
					this._Nam = value;
					this.SendPropertyChanged("Nam");
					this.OnNamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adr", DbType="NVarChar(50)")]
		public string Adr
		{
			get
			{
				return this._Adr;
			}
			set
			{
				if ((this._Adr != value))
				{
					this.OnAdrChanging(value);
					this.SendPropertyChanging();
					this._Adr = value;
					this.SendPropertyChanged("Adr");
					this.OnAdrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loc", DbType="NVarChar(50)")]
		public string Loc
		{
			get
			{
				return this._Loc;
			}
			set
			{
				if ((this._Loc != value))
				{
					this.OnLocChanging(value);
					this.SendPropertyChanging();
					this._Loc = value;
					this.SendPropertyChanged("Loc");
					this.OnLocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel", DbType="NVarChar(50)")]
		public string Tel
		{
			get
			{
				return this._Tel;
			}
			set
			{
				if ((this._Tel != value))
				{
					this.OnTelChanging(value);
					this.SendPropertyChanging();
					this._Tel = value;
					this.SendPropertyChanged("Tel");
					this.OnTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Clas", DbType="Char(1) NOT NULL")]
		public char Clas
		{
			get
			{
				return this._Clas;
			}
			set
			{
				if ((this._Clas != value))
				{
					this.OnClasChanging(value);
					this.SendPropertyChanging();
					this._Clas = value;
					this.SendPropertyChanged("Clas");
					this.OnClasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Form", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string Form
		{
			get
			{
				return this._Form;
			}
			set
			{
				if ((this._Form != value))
				{
					this.OnFormChanging(value);
					this.SendPropertyChanging();
					this._Form = value;
					this.SendPropertyChanged("Form");
					this.OnFormChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Typ", DbType="Char(1) NOT NULL")]
		public char Typ
		{
			get
			{
				return this._Typ;
			}
			set
			{
				if ((this._Typ != value))
				{
					this.OnTypChanging(value);
					this.SendPropertyChanging();
					this._Typ = value;
					this.SendPropertyChanged("Typ");
					this.OnTypChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_end_date", DbType="VarChar(8)")]
		public string end_date
		{
			get
			{
				return this._end_date;
			}
			set
			{
				if ((this._end_date != value))
				{
					this.Onend_dateChanging(value);
					this.SendPropertyChanging();
					this._end_date = value;
					this.SendPropertyChanged("end_date");
					this.Onend_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stat", DbType="Char(1)")]
		public System.Nullable<char> Stat
		{
			get
			{
				return this._Stat;
			}
			set
			{
				if ((this._Stat != value))
				{
					this.OnStatChanging(value);
					this.SendPropertyChanging();
					this._Stat = value;
					this.SendPropertyChanged("Stat");
					this.OnStatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QDATE", DbType="DateTime NOT NULL")]
		public System.DateTime QDATE
		{
			get
			{
				return this._QDATE;
			}
			set
			{
				if ((this._QDATE != value))
				{
					this.OnQDATEChanging(value);
					this.SendPropertyChanging();
					this._QDATE = value;
					this.SendPropertyChanged("QDATE");
					this.OnQDATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
