#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSysteMc.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="al")]
	public partial class CSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 擴充性方法定義
    partial void OnCreated();
    partial void Insertlog_Adm(log_Adm instance);
    partial void Updatelog_Adm(log_Adm instance);
    partial void Deletelog_Adm(log_Adm instance);
    partial void Insertlog_Err(log_Err instance);
    partial void Updatelog_Err(log_Err instance);
    partial void Deletelog_Err(log_Err instance);
    partial void Inserttbl_opd(tbl_opd instance);
    partial void Updatetbl_opd(tbl_opd instance);
    partial void Deletetbl_opd(tbl_opd instance);
    partial void Inserttbl_opd_order(tbl_opd_order instance);
    partial void Updatetbl_opd_order(tbl_opd_order instance);
    partial void Deletetbl_opd_order(tbl_opd_order instance);
    #endregion
		
		public CSDataContext() : 
				base(global::ClinicSysteMc.Properties.Settings.Default.alConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<log_Adm> log_Adm
		{
			get
			{
				return this.GetTable<log_Adm>();
			}
		}
		
		public System.Data.Linq.Table<log_Err> log_Err
		{
			get
			{
				return this.GetTable<log_Err>();
			}
		}
		
		public System.Data.Linq.Table<v_labdata_not_match_with_opd_order> v_labdata_not_match_with_opd_order
		{
			get
			{
				return this.GetTable<v_labdata_not_match_with_opd_order>();
			}
		}
		
		public System.Data.Linq.Table<v_opdorder_not_match_with_lab_record> v_opdorder_not_match_with_lab_record
		{
			get
			{
				return this.GetTable<v_opdorder_not_match_with_lab_record>();
			}
		}
		
		public System.Data.Linq.Table<tbl_opd> tbl_opd
		{
			get
			{
				return this.GetTable<tbl_opd>();
			}
		}
		
		public System.Data.Linq.Table<tbl_opd_order> tbl_opd_order
		{
			get
			{
				return this.GetTable<tbl_opd_order>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.log_Adm")]
	public partial class log_Adm : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _access_id;
		
		private System.DateTime _regdate;
		
		private string _application_name;
		
		private string _machine_name;
		
		private string _ip_address;
		
		private string _userid;
		
		private string _operation_name;
		
		private string _description;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onaccess_idChanging(long value);
    partial void Onaccess_idChanged();
    partial void OnregdateChanging(System.DateTime value);
    partial void OnregdateChanged();
    partial void Onapplication_nameChanging(string value);
    partial void Onapplication_nameChanged();
    partial void Onmachine_nameChanging(string value);
    partial void Onmachine_nameChanged();
    partial void Onip_addressChanging(string value);
    partial void Onip_addressChanged();
    partial void OnuseridChanging(string value);
    partial void OnuseridChanged();
    partial void Onoperation_nameChanging(string value);
    partial void Onoperation_nameChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    #endregion
		
		public log_Adm()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_access_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long access_id
		{
			get
			{
				return this._access_id;
			}
			set
			{
				if ((this._access_id != value))
				{
					this.Onaccess_idChanging(value);
					this.SendPropertyChanging();
					this._access_id = value;
					this.SendPropertyChanged("access_id");
					this.Onaccess_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_regdate", DbType="DateTime NOT NULL")]
		public System.DateTime regdate
		{
			get
			{
				return this._regdate;
			}
			set
			{
				if ((this._regdate != value))
				{
					this.OnregdateChanging(value);
					this.SendPropertyChanging();
					this._regdate = value;
					this.SendPropertyChanged("regdate");
					this.OnregdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_application_name", DbType="NVarChar(50)")]
		public string application_name
		{
			get
			{
				return this._application_name;
			}
			set
			{
				if ((this._application_name != value))
				{
					this.Onapplication_nameChanging(value);
					this.SendPropertyChanging();
					this._application_name = value;
					this.SendPropertyChanged("application_name");
					this.Onapplication_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_machine_name", DbType="NVarChar(50)")]
		public string machine_name
		{
			get
			{
				return this._machine_name;
			}
			set
			{
				if ((this._machine_name != value))
				{
					this.Onmachine_nameChanging(value);
					this.SendPropertyChanging();
					this._machine_name = value;
					this.SendPropertyChanged("machine_name");
					this.Onmachine_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ip_address", DbType="NVarChar(50)")]
		public string ip_address
		{
			get
			{
				return this._ip_address;
			}
			set
			{
				if ((this._ip_address != value))
				{
					this.Onip_addressChanging(value);
					this.SendPropertyChanging();
					this._ip_address = value;
					this.SendPropertyChanged("ip_address");
					this.Onip_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this.OnuseridChanging(value);
					this.SendPropertyChanging();
					this._userid = value;
					this.SendPropertyChanged("userid");
					this.OnuseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_operation_name", DbType="NVarChar(50)")]
		public string operation_name
		{
			get
			{
				return this._operation_name;
			}
			set
			{
				if ((this._operation_name != value))
				{
					this.Onoperation_nameChanging(value);
					this.SendPropertyChanging();
					this._operation_name = value;
					this.SendPropertyChanged("operation_name");
					this.Onoperation_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.log_Err")]
	public partial class log_Err : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _error_id;
		
		private System.DateTime _error_date;
		
		private string _application_name;
		
		private string _machine_name;
		
		private string _ip_address;
		
		private string _userid;
		
		private string _error_message;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onerror_idChanging(long value);
    partial void Onerror_idChanged();
    partial void Onerror_dateChanging(System.DateTime value);
    partial void Onerror_dateChanged();
    partial void Onapplication_nameChanging(string value);
    partial void Onapplication_nameChanged();
    partial void Onmachine_nameChanging(string value);
    partial void Onmachine_nameChanged();
    partial void Onip_addressChanging(string value);
    partial void Onip_addressChanged();
    partial void OnuseridChanging(string value);
    partial void OnuseridChanged();
    partial void Onerror_messageChanging(string value);
    partial void Onerror_messageChanged();
    #endregion
		
		public log_Err()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_error_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long error_id
		{
			get
			{
				return this._error_id;
			}
			set
			{
				if ((this._error_id != value))
				{
					this.Onerror_idChanging(value);
					this.SendPropertyChanging();
					this._error_id = value;
					this.SendPropertyChanged("error_id");
					this.Onerror_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_error_date", DbType="DateTime NOT NULL")]
		public System.DateTime error_date
		{
			get
			{
				return this._error_date;
			}
			set
			{
				if ((this._error_date != value))
				{
					this.Onerror_dateChanging(value);
					this.SendPropertyChanging();
					this._error_date = value;
					this.SendPropertyChanged("error_date");
					this.Onerror_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_application_name", DbType="NVarChar(50)")]
		public string application_name
		{
			get
			{
				return this._application_name;
			}
			set
			{
				if ((this._application_name != value))
				{
					this.Onapplication_nameChanging(value);
					this.SendPropertyChanging();
					this._application_name = value;
					this.SendPropertyChanged("application_name");
					this.Onapplication_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_machine_name", DbType="NVarChar(50)")]
		public string machine_name
		{
			get
			{
				return this._machine_name;
			}
			set
			{
				if ((this._machine_name != value))
				{
					this.Onmachine_nameChanging(value);
					this.SendPropertyChanging();
					this._machine_name = value;
					this.SendPropertyChanged("machine_name");
					this.Onmachine_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ip_address", DbType="NVarChar(50)")]
		public string ip_address
		{
			get
			{
				return this._ip_address;
			}
			set
			{
				if ((this._ip_address != value))
				{
					this.Onip_addressChanging(value);
					this.SendPropertyChanging();
					this._ip_address = value;
					this.SendPropertyChanged("ip_address");
					this.Onip_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this.OnuseridChanging(value);
					this.SendPropertyChanging();
					this._userid = value;
					this.SendPropertyChanged("userid");
					this.OnuseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_error_message", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string error_message
		{
			get
			{
				return this._error_message;
			}
			set
			{
				if ((this._error_message != value))
				{
					this.Onerror_messageChanging(value);
					this.SendPropertyChanging();
					this._error_message = value;
					this.SendPropertyChanged("error_message");
					this.Onerror_messageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_labdata_not_match_with_opd_order")]
	public partial class v_labdata_not_match_with_opd_order
	{
		
		private string _lid;
		
		private string _uid;
		
		private string _cname;
		
		private System.Nullable<System.DateTime> _l05;
		
		private string _iid;
		
		private string _nhi_code;
		
		private string _l07;
		
		private string _l09;
		
		private string _l08;
		
		public v_labdata_not_match_with_opd_order()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lid", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string lid
		{
			get
			{
				return this._lid;
			}
			set
			{
				if ((this._lid != value))
				{
					this._lid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this._uid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cname", DbType="NVarChar(50)")]
		public string cname
		{
			get
			{
				return this._cname;
			}
			set
			{
				if ((this._cname != value))
				{
					this._cname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l05", DbType="Date")]
		public System.Nullable<System.DateTime> l05
		{
			get
			{
				return this._l05;
			}
			set
			{
				if ((this._l05 != value))
				{
					this._l05 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iid", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string iid
		{
			get
			{
				return this._iid;
			}
			set
			{
				if ((this._iid != value))
				{
					this._iid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nhi_code", DbType="NVarChar(50)")]
		public string nhi_code
		{
			get
			{
				return this._nhi_code;
			}
			set
			{
				if ((this._nhi_code != value))
				{
					this._nhi_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l07", DbType="NVarChar(50)")]
		public string l07
		{
			get
			{
				return this._l07;
			}
			set
			{
				if ((this._l07 != value))
				{
					this._l07 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l09", DbType="NVarChar(50)")]
		public string l09
		{
			get
			{
				return this._l09;
			}
			set
			{
				if ((this._l09 != value))
				{
					this._l09 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l08", DbType="NVarChar(255)")]
		public string l08
		{
			get
			{
				return this._l08;
			}
			set
			{
				if ((this._l08 != value))
				{
					this._l08 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_opdorder_not_match_with_lab_record")]
	public partial class v_opdorder_not_match_with_lab_record
	{
		
		private string _CASENO;
		
		private string _uid;
		
		private string _cname;
		
		private System.Nullable<System.DateTime> _SDATE;
		
		private byte _OD_idx;
		
		private string _rid;
		
		private string _l08;
		
		public v_opdorder_not_match_with_lab_record()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CASENO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CASENO
		{
			get
			{
				return this._CASENO;
			}
			set
			{
				if ((this._CASENO != value))
				{
					this._CASENO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", DbType="NVarChar(50)")]
		public string uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this._uid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cname", DbType="NVarChar(50)")]
		public string cname
		{
			get
			{
				return this._cname;
			}
			set
			{
				if ((this._cname != value))
				{
					this._cname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDATE", DbType="Date")]
		public System.Nullable<System.DateTime> SDATE
		{
			get
			{
				return this._SDATE;
			}
			set
			{
				if ((this._SDATE != value))
				{
					this._SDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OD_idx", DbType="TinyInt NOT NULL")]
		public byte OD_idx
		{
			get
			{
				return this._OD_idx;
			}
			set
			{
				if ((this._OD_idx != value))
				{
					this._OD_idx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rid", DbType="NVarChar(50)")]
		public string rid
		{
			get
			{
				return this._rid;
			}
			set
			{
				if ((this._rid != value))
				{
					this._rid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l08", DbType="NVarChar(255)")]
		public string l08
		{
			get
			{
				return this._l08;
			}
			set
			{
				if ((this._l08 != value))
				{
					this._l08 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_opd")]
	public partial class tbl_opd : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CASENO;
		
		private System.Nullable<System.DateTime> _SDATE;
		
		private string _VIST;
		
		private System.Nullable<byte> _RMNO;
		
		private string _uid;
		
		private string _DEPTNAME;
		
		private string _DOCTNAME;
		
		private string _POSINAME;
		
		private string _PAYNO;
		
		private string _HEATH_CARD;
		
		private string _ICDCODE1;
		
		private string _ICDCODE2;
		
		private string _ICDCODE3;
		
		private string _INS_CODE;
		
		private string _STEXT;
		
		private string _OTEXT;
		
		private string _Pijia;
		
		private string _t3;
		
		private string _d1;
		
		private System.Nullable<int> _d2;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCASENOChanging(string value);
    partial void OnCASENOChanged();
    partial void OnSDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSDATEChanged();
    partial void OnVISTChanging(string value);
    partial void OnVISTChanged();
    partial void OnRMNOChanging(System.Nullable<byte> value);
    partial void OnRMNOChanged();
    partial void OnuidChanging(string value);
    partial void OnuidChanged();
    partial void OnDEPTNAMEChanging(string value);
    partial void OnDEPTNAMEChanged();
    partial void OnDOCTNAMEChanging(string value);
    partial void OnDOCTNAMEChanged();
    partial void OnPOSINAMEChanging(string value);
    partial void OnPOSINAMEChanged();
    partial void OnPAYNOChanging(string value);
    partial void OnPAYNOChanged();
    partial void OnHEATH_CARDChanging(string value);
    partial void OnHEATH_CARDChanged();
    partial void OnICDCODE1Changing(string value);
    partial void OnICDCODE1Changed();
    partial void OnICDCODE2Changing(string value);
    partial void OnICDCODE2Changed();
    partial void OnICDCODE3Changing(string value);
    partial void OnICDCODE3Changed();
    partial void OnINS_CODEChanging(string value);
    partial void OnINS_CODEChanged();
    partial void OnSTEXTChanging(string value);
    partial void OnSTEXTChanged();
    partial void OnOTEXTChanging(string value);
    partial void OnOTEXTChanged();
    partial void OnPijiaChanging(string value);
    partial void OnPijiaChanged();
    partial void Ont3Changing(string value);
    partial void Ont3Changed();
    partial void Ond1Changing(string value);
    partial void Ond1Changed();
    partial void Ond2Changing(System.Nullable<int> value);
    partial void Ond2Changed();
    #endregion
		
		public tbl_opd()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CASENO", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CASENO
		{
			get
			{
				return this._CASENO;
			}
			set
			{
				if ((this._CASENO != value))
				{
					this.OnCASENOChanging(value);
					this.SendPropertyChanging();
					this._CASENO = value;
					this.SendPropertyChanged("CASENO");
					this.OnCASENOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDATE", DbType="Date")]
		public System.Nullable<System.DateTime> SDATE
		{
			get
			{
				return this._SDATE;
			}
			set
			{
				if ((this._SDATE != value))
				{
					this.OnSDATEChanging(value);
					this.SendPropertyChanging();
					this._SDATE = value;
					this.SendPropertyChanged("SDATE");
					this.OnSDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VIST", DbType="NVarChar(50)")]
		public string VIST
		{
			get
			{
				return this._VIST;
			}
			set
			{
				if ((this._VIST != value))
				{
					this.OnVISTChanging(value);
					this.SendPropertyChanging();
					this._VIST = value;
					this.SendPropertyChanged("VIST");
					this.OnVISTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RMNO", DbType="TinyInt")]
		public System.Nullable<byte> RMNO
		{
			get
			{
				return this._RMNO;
			}
			set
			{
				if ((this._RMNO != value))
				{
					this.OnRMNOChanging(value);
					this.SendPropertyChanging();
					this._RMNO = value;
					this.SendPropertyChanged("RMNO");
					this.OnRMNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", DbType="NVarChar(50)")]
		public string uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this.OnuidChanging(value);
					this.SendPropertyChanging();
					this._uid = value;
					this.SendPropertyChanged("uid");
					this.OnuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPTNAME", DbType="NVarChar(50)")]
		public string DEPTNAME
		{
			get
			{
				return this._DEPTNAME;
			}
			set
			{
				if ((this._DEPTNAME != value))
				{
					this.OnDEPTNAMEChanging(value);
					this.SendPropertyChanging();
					this._DEPTNAME = value;
					this.SendPropertyChanged("DEPTNAME");
					this.OnDEPTNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCTNAME", DbType="NVarChar(50)")]
		public string DOCTNAME
		{
			get
			{
				return this._DOCTNAME;
			}
			set
			{
				if ((this._DOCTNAME != value))
				{
					this.OnDOCTNAMEChanging(value);
					this.SendPropertyChanging();
					this._DOCTNAME = value;
					this.SendPropertyChanged("DOCTNAME");
					this.OnDOCTNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSINAME", DbType="NVarChar(50)")]
		public string POSINAME
		{
			get
			{
				return this._POSINAME;
			}
			set
			{
				if ((this._POSINAME != value))
				{
					this.OnPOSINAMEChanging(value);
					this.SendPropertyChanging();
					this._POSINAME = value;
					this.SendPropertyChanged("POSINAME");
					this.OnPOSINAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAYNO", DbType="NVarChar(50)")]
		public string PAYNO
		{
			get
			{
				return this._PAYNO;
			}
			set
			{
				if ((this._PAYNO != value))
				{
					this.OnPAYNOChanging(value);
					this.SendPropertyChanging();
					this._PAYNO = value;
					this.SendPropertyChanged("PAYNO");
					this.OnPAYNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HEATH_CARD", DbType="NVarChar(50)")]
		public string HEATH_CARD
		{
			get
			{
				return this._HEATH_CARD;
			}
			set
			{
				if ((this._HEATH_CARD != value))
				{
					this.OnHEATH_CARDChanging(value);
					this.SendPropertyChanging();
					this._HEATH_CARD = value;
					this.SendPropertyChanged("HEATH_CARD");
					this.OnHEATH_CARDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ICDCODE1", DbType="NVarChar(50)")]
		public string ICDCODE1
		{
			get
			{
				return this._ICDCODE1;
			}
			set
			{
				if ((this._ICDCODE1 != value))
				{
					this.OnICDCODE1Changing(value);
					this.SendPropertyChanging();
					this._ICDCODE1 = value;
					this.SendPropertyChanged("ICDCODE1");
					this.OnICDCODE1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ICDCODE2", DbType="NVarChar(50)")]
		public string ICDCODE2
		{
			get
			{
				return this._ICDCODE2;
			}
			set
			{
				if ((this._ICDCODE2 != value))
				{
					this.OnICDCODE2Changing(value);
					this.SendPropertyChanging();
					this._ICDCODE2 = value;
					this.SendPropertyChanged("ICDCODE2");
					this.OnICDCODE2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ICDCODE3", DbType="NVarChar(50)")]
		public string ICDCODE3
		{
			get
			{
				return this._ICDCODE3;
			}
			set
			{
				if ((this._ICDCODE3 != value))
				{
					this.OnICDCODE3Changing(value);
					this.SendPropertyChanging();
					this._ICDCODE3 = value;
					this.SendPropertyChanged("ICDCODE3");
					this.OnICDCODE3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INS_CODE", DbType="NVarChar(50)")]
		public string INS_CODE
		{
			get
			{
				return this._INS_CODE;
			}
			set
			{
				if ((this._INS_CODE != value))
				{
					this.OnINS_CODEChanging(value);
					this.SendPropertyChanging();
					this._INS_CODE = value;
					this.SendPropertyChanged("INS_CODE");
					this.OnINS_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STEXT", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string STEXT
		{
			get
			{
				return this._STEXT;
			}
			set
			{
				if ((this._STEXT != value))
				{
					this.OnSTEXTChanging(value);
					this.SendPropertyChanging();
					this._STEXT = value;
					this.SendPropertyChanged("STEXT");
					this.OnSTEXTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OTEXT", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string OTEXT
		{
			get
			{
				return this._OTEXT;
			}
			set
			{
				if ((this._OTEXT != value))
				{
					this.OnOTEXTChanging(value);
					this.SendPropertyChanging();
					this._OTEXT = value;
					this.SendPropertyChanged("OTEXT");
					this.OnOTEXTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pijia", DbType="NVarChar(50)")]
		public string Pijia
		{
			get
			{
				return this._Pijia;
			}
			set
			{
				if ((this._Pijia != value))
				{
					this.OnPijiaChanging(value);
					this.SendPropertyChanging();
					this._Pijia = value;
					this.SendPropertyChanged("Pijia");
					this.OnPijiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t3", DbType="NChar(5)")]
		public string t3
		{
			get
			{
				return this._t3;
			}
			set
			{
				if ((this._t3 != value))
				{
					this.Ont3Changing(value);
					this.SendPropertyChanging();
					this._t3 = value;
					this.SendPropertyChanged("t3");
					this.Ont3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d1", DbType="NChar(2)")]
		public string d1
		{
			get
			{
				return this._d1;
			}
			set
			{
				if ((this._d1 != value))
				{
					this.Ond1Changing(value);
					this.SendPropertyChanging();
					this._d1 = value;
					this.SendPropertyChanged("d1");
					this.Ond1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d2", DbType="Int")]
		public System.Nullable<int> d2
		{
			get
			{
				return this._d2;
			}
			set
			{
				if ((this._d2 != value))
				{
					this.Ond2Changing(value);
					this.SendPropertyChanging();
					this._d2 = value;
					this.SendPropertyChanged("d2");
					this.Ond2Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_opd_order")]
	public partial class tbl_opd_order : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CASENO;
		
		private string _uid;
		
		private System.Nullable<System.DateTime> _SDATE;
		
		private byte _OD_idx;
		
		private string _rid;
		
		private string _TIMES_DAY;
		
		private string _METHOD;
		
		private string _TIME_QTY1;
		
		private string _DAYS;
		
		private string _BILL_QTY;
		
		private string _HC;
		
		private string _PRICE;
		
		private string _AMT;
		
		private string _CLASS;
		
		private string _CHRONIC;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCASENOChanging(string value);
    partial void OnCASENOChanged();
    partial void OnuidChanging(string value);
    partial void OnuidChanged();
    partial void OnSDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSDATEChanged();
    partial void OnOD_idxChanging(byte value);
    partial void OnOD_idxChanged();
    partial void OnridChanging(string value);
    partial void OnridChanged();
    partial void OnTIMES_DAYChanging(string value);
    partial void OnTIMES_DAYChanged();
    partial void OnMETHODChanging(string value);
    partial void OnMETHODChanged();
    partial void OnTIME_QTY1Changing(string value);
    partial void OnTIME_QTY1Changed();
    partial void OnDAYSChanging(string value);
    partial void OnDAYSChanged();
    partial void OnBILL_QTYChanging(string value);
    partial void OnBILL_QTYChanged();
    partial void OnHCChanging(string value);
    partial void OnHCChanged();
    partial void OnPRICEChanging(string value);
    partial void OnPRICEChanged();
    partial void OnAMTChanging(string value);
    partial void OnAMTChanged();
    partial void OnCLASSChanging(string value);
    partial void OnCLASSChanged();
    partial void OnCHRONICChanging(string value);
    partial void OnCHRONICChanged();
    #endregion
		
		public tbl_opd_order()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CASENO", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CASENO
		{
			get
			{
				return this._CASENO;
			}
			set
			{
				if ((this._CASENO != value))
				{
					this.OnCASENOChanging(value);
					this.SendPropertyChanging();
					this._CASENO = value;
					this.SendPropertyChanged("CASENO");
					this.OnCASENOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", DbType="NVarChar(50)")]
		public string uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this.OnuidChanging(value);
					this.SendPropertyChanging();
					this._uid = value;
					this.SendPropertyChanged("uid");
					this.OnuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDATE", DbType="Date")]
		public System.Nullable<System.DateTime> SDATE
		{
			get
			{
				return this._SDATE;
			}
			set
			{
				if ((this._SDATE != value))
				{
					this.OnSDATEChanging(value);
					this.SendPropertyChanging();
					this._SDATE = value;
					this.SendPropertyChanged("SDATE");
					this.OnSDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OD_idx", DbType="TinyInt NOT NULL", IsPrimaryKey=true)]
		public byte OD_idx
		{
			get
			{
				return this._OD_idx;
			}
			set
			{
				if ((this._OD_idx != value))
				{
					this.OnOD_idxChanging(value);
					this.SendPropertyChanging();
					this._OD_idx = value;
					this.SendPropertyChanged("OD_idx");
					this.OnOD_idxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rid", DbType="NVarChar(50)")]
		public string rid
		{
			get
			{
				return this._rid;
			}
			set
			{
				if ((this._rid != value))
				{
					this.OnridChanging(value);
					this.SendPropertyChanging();
					this._rid = value;
					this.SendPropertyChanged("Rid");
					this.OnridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIMES_DAY", DbType="NVarChar(50)")]
		public string TIMES_DAY
		{
			get
			{
				return this._TIMES_DAY;
			}
			set
			{
				if ((this._TIMES_DAY != value))
				{
					this.OnTIMES_DAYChanging(value);
					this.SendPropertyChanging();
					this._TIMES_DAY = value;
					this.SendPropertyChanged("TIMES_DAY");
					this.OnTIMES_DAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_METHOD", DbType="NVarChar(50)")]
		public string METHOD
		{
			get
			{
				return this._METHOD;
			}
			set
			{
				if ((this._METHOD != value))
				{
					this.OnMETHODChanging(value);
					this.SendPropertyChanging();
					this._METHOD = value;
					this.SendPropertyChanged("METHOD");
					this.OnMETHODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIME_QTY1", DbType="NVarChar(50)")]
		public string TIME_QTY1
		{
			get
			{
				return this._TIME_QTY1;
			}
			set
			{
				if ((this._TIME_QTY1 != value))
				{
					this.OnTIME_QTY1Changing(value);
					this.SendPropertyChanging();
					this._TIME_QTY1 = value;
					this.SendPropertyChanged("TIME_QTY1");
					this.OnTIME_QTY1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DAYS", DbType="NVarChar(50)")]
		public string DAYS
		{
			get
			{
				return this._DAYS;
			}
			set
			{
				if ((this._DAYS != value))
				{
					this.OnDAYSChanging(value);
					this.SendPropertyChanging();
					this._DAYS = value;
					this.SendPropertyChanged("DAYS");
					this.OnDAYSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BILL_QTY", DbType="NVarChar(50)")]
		public string BILL_QTY
		{
			get
			{
				return this._BILL_QTY;
			}
			set
			{
				if ((this._BILL_QTY != value))
				{
					this.OnBILL_QTYChanging(value);
					this.SendPropertyChanging();
					this._BILL_QTY = value;
					this.SendPropertyChanged("BILL_QTY");
					this.OnBILL_QTYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HC", DbType="NVarChar(50)")]
		public string HC
		{
			get
			{
				return this._HC;
			}
			set
			{
				if ((this._HC != value))
				{
					this.OnHCChanging(value);
					this.SendPropertyChanging();
					this._HC = value;
					this.SendPropertyChanged("HC");
					this.OnHCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRICE", DbType="NVarChar(50)")]
		public string PRICE
		{
			get
			{
				return this._PRICE;
			}
			set
			{
				if ((this._PRICE != value))
				{
					this.OnPRICEChanging(value);
					this.SendPropertyChanging();
					this._PRICE = value;
					this.SendPropertyChanged("PRICE");
					this.OnPRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AMT", DbType="NVarChar(50)")]
		public string AMT
		{
			get
			{
				return this._AMT;
			}
			set
			{
				if ((this._AMT != value))
				{
					this.OnAMTChanging(value);
					this.SendPropertyChanging();
					this._AMT = value;
					this.SendPropertyChanged("AMT");
					this.OnAMTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASS", DbType="NVarChar(50)")]
		public string CLASS
		{
			get
			{
				return this._CLASS;
			}
			set
			{
				if ((this._CLASS != value))
				{
					this.OnCLASSChanging(value);
					this.SendPropertyChanging();
					this._CLASS = value;
					this.SendPropertyChanged("CLASS");
					this.OnCLASSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHRONIC", DbType="NVarChar(50)")]
		public string CHRONIC
		{
			get
			{
				return this._CHRONIC;
			}
			set
			{
				if ((this._CHRONIC != value))
				{
					this.OnCHRONICChanging(value);
					this.SendPropertyChanging();
					this._CHRONIC = value;
					this.SendPropertyChanged("CHRONIC");
					this.OnCHRONICChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
