#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSysteMc.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="al")]
	public partial class CSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 擴充性方法定義
    partial void OnCreated();
    partial void Insertlog_Adm(log_Adm instance);
    partial void Updatelog_Adm(log_Adm instance);
    partial void Deletelog_Adm(log_Adm instance);
    partial void Insertlog_Err(log_Err instance);
    partial void Updatelog_Err(log_Err instance);
    partial void Deletelog_Err(log_Err instance);
    #endregion
		
		public CSDataContext() : 
				base(global::ClinicSysteMc.Properties.Settings.Default.alConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<log_Adm> log_Adm
		{
			get
			{
				return this.GetTable<log_Adm>();
			}
		}
		
		public System.Data.Linq.Table<log_Err> log_Err
		{
			get
			{
				return this.GetTable<log_Err>();
			}
		}
		
		public System.Data.Linq.Table<v_labdata_not_match_with_opd_order> v_labdata_not_match_with_opd_order
		{
			get
			{
				return this.GetTable<v_labdata_not_match_with_opd_order>();
			}
		}
		
		public System.Data.Linq.Table<v_opdorder_not_match_with_lab_record> v_opdorder_not_match_with_lab_record
		{
			get
			{
				return this.GetTable<v_opdorder_not_match_with_lab_record>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.log_Adm")]
	public partial class log_Adm : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _access_id;
		
		private System.DateTime _regdate;
		
		private string _application_name;
		
		private string _machine_name;
		
		private string _ip_address;
		
		private string _userid;
		
		private string _operation_name;
		
		private string _description;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onaccess_idChanging(long value);
    partial void Onaccess_idChanged();
    partial void OnregdateChanging(System.DateTime value);
    partial void OnregdateChanged();
    partial void Onapplication_nameChanging(string value);
    partial void Onapplication_nameChanged();
    partial void Onmachine_nameChanging(string value);
    partial void Onmachine_nameChanged();
    partial void Onip_addressChanging(string value);
    partial void Onip_addressChanged();
    partial void OnuseridChanging(string value);
    partial void OnuseridChanged();
    partial void Onoperation_nameChanging(string value);
    partial void Onoperation_nameChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    #endregion
		
		public log_Adm()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_access_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long access_id
		{
			get
			{
				return this._access_id;
			}
			set
			{
				if ((this._access_id != value))
				{
					this.Onaccess_idChanging(value);
					this.SendPropertyChanging();
					this._access_id = value;
					this.SendPropertyChanged("access_id");
					this.Onaccess_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_regdate", DbType="DateTime NOT NULL")]
		public System.DateTime regdate
		{
			get
			{
				return this._regdate;
			}
			set
			{
				if ((this._regdate != value))
				{
					this.OnregdateChanging(value);
					this.SendPropertyChanging();
					this._regdate = value;
					this.SendPropertyChanged("regdate");
					this.OnregdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_application_name", DbType="NVarChar(50)")]
		public string application_name
		{
			get
			{
				return this._application_name;
			}
			set
			{
				if ((this._application_name != value))
				{
					this.Onapplication_nameChanging(value);
					this.SendPropertyChanging();
					this._application_name = value;
					this.SendPropertyChanged("application_name");
					this.Onapplication_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_machine_name", DbType="NVarChar(50)")]
		public string machine_name
		{
			get
			{
				return this._machine_name;
			}
			set
			{
				if ((this._machine_name != value))
				{
					this.Onmachine_nameChanging(value);
					this.SendPropertyChanging();
					this._machine_name = value;
					this.SendPropertyChanged("machine_name");
					this.Onmachine_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ip_address", DbType="NVarChar(50)")]
		public string ip_address
		{
			get
			{
				return this._ip_address;
			}
			set
			{
				if ((this._ip_address != value))
				{
					this.Onip_addressChanging(value);
					this.SendPropertyChanging();
					this._ip_address = value;
					this.SendPropertyChanged("ip_address");
					this.Onip_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this.OnuseridChanging(value);
					this.SendPropertyChanging();
					this._userid = value;
					this.SendPropertyChanged("userid");
					this.OnuseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_operation_name", DbType="NVarChar(50)")]
		public string operation_name
		{
			get
			{
				return this._operation_name;
			}
			set
			{
				if ((this._operation_name != value))
				{
					this.Onoperation_nameChanging(value);
					this.SendPropertyChanging();
					this._operation_name = value;
					this.SendPropertyChanged("operation_name");
					this.Onoperation_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.log_Err")]
	public partial class log_Err : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _error_id;
		
		private System.DateTime _error_date;
		
		private string _application_name;
		
		private string _machine_name;
		
		private string _ip_address;
		
		private string _userid;
		
		private string _error_message;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onerror_idChanging(long value);
    partial void Onerror_idChanged();
    partial void Onerror_dateChanging(System.DateTime value);
    partial void Onerror_dateChanged();
    partial void Onapplication_nameChanging(string value);
    partial void Onapplication_nameChanged();
    partial void Onmachine_nameChanging(string value);
    partial void Onmachine_nameChanged();
    partial void Onip_addressChanging(string value);
    partial void Onip_addressChanged();
    partial void OnuseridChanging(string value);
    partial void OnuseridChanged();
    partial void Onerror_messageChanging(string value);
    partial void Onerror_messageChanged();
    #endregion
		
		public log_Err()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_error_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long error_id
		{
			get
			{
				return this._error_id;
			}
			set
			{
				if ((this._error_id != value))
				{
					this.Onerror_idChanging(value);
					this.SendPropertyChanging();
					this._error_id = value;
					this.SendPropertyChanged("error_id");
					this.Onerror_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_error_date", DbType="DateTime NOT NULL")]
		public System.DateTime error_date
		{
			get
			{
				return this._error_date;
			}
			set
			{
				if ((this._error_date != value))
				{
					this.Onerror_dateChanging(value);
					this.SendPropertyChanging();
					this._error_date = value;
					this.SendPropertyChanged("error_date");
					this.Onerror_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_application_name", DbType="NVarChar(50)")]
		public string application_name
		{
			get
			{
				return this._application_name;
			}
			set
			{
				if ((this._application_name != value))
				{
					this.Onapplication_nameChanging(value);
					this.SendPropertyChanging();
					this._application_name = value;
					this.SendPropertyChanged("application_name");
					this.Onapplication_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_machine_name", DbType="NVarChar(50)")]
		public string machine_name
		{
			get
			{
				return this._machine_name;
			}
			set
			{
				if ((this._machine_name != value))
				{
					this.Onmachine_nameChanging(value);
					this.SendPropertyChanging();
					this._machine_name = value;
					this.SendPropertyChanged("machine_name");
					this.Onmachine_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ip_address", DbType="NVarChar(50)")]
		public string ip_address
		{
			get
			{
				return this._ip_address;
			}
			set
			{
				if ((this._ip_address != value))
				{
					this.Onip_addressChanging(value);
					this.SendPropertyChanging();
					this._ip_address = value;
					this.SendPropertyChanged("ip_address");
					this.Onip_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this.OnuseridChanging(value);
					this.SendPropertyChanging();
					this._userid = value;
					this.SendPropertyChanged("userid");
					this.OnuseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_error_message", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string error_message
		{
			get
			{
				return this._error_message;
			}
			set
			{
				if ((this._error_message != value))
				{
					this.Onerror_messageChanging(value);
					this.SendPropertyChanging();
					this._error_message = value;
					this.SendPropertyChanged("error_message");
					this.Onerror_messageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_labdata_not_match_with_opd_order")]
	public partial class v_labdata_not_match_with_opd_order
	{
		
		private string _lid;
		
		private string _uid;
		
		private string _cname;
		
		private System.Nullable<System.DateTime> _l05;
		
		private string _iid;
		
		private string _nhi_code;
		
		private string _l07;
		
		private string _l09;
		
		private string _l08;
		
		public v_labdata_not_match_with_opd_order()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lid", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string lid
		{
			get
			{
				return this._lid;
			}
			set
			{
				if ((this._lid != value))
				{
					this._lid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this._uid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cname", DbType="NVarChar(50)")]
		public string cname
		{
			get
			{
				return this._cname;
			}
			set
			{
				if ((this._cname != value))
				{
					this._cname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l05", DbType="Date")]
		public System.Nullable<System.DateTime> l05
		{
			get
			{
				return this._l05;
			}
			set
			{
				if ((this._l05 != value))
				{
					this._l05 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iid", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string iid
		{
			get
			{
				return this._iid;
			}
			set
			{
				if ((this._iid != value))
				{
					this._iid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nhi_code", DbType="NVarChar(50)")]
		public string nhi_code
		{
			get
			{
				return this._nhi_code;
			}
			set
			{
				if ((this._nhi_code != value))
				{
					this._nhi_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l07", DbType="NVarChar(50)")]
		public string l07
		{
			get
			{
				return this._l07;
			}
			set
			{
				if ((this._l07 != value))
				{
					this._l07 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l09", DbType="NVarChar(50)")]
		public string l09
		{
			get
			{
				return this._l09;
			}
			set
			{
				if ((this._l09 != value))
				{
					this._l09 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l08", DbType="NVarChar(255)")]
		public string l08
		{
			get
			{
				return this._l08;
			}
			set
			{
				if ((this._l08 != value))
				{
					this._l08 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_opdorder_not_match_with_lab_record")]
	public partial class v_opdorder_not_match_with_lab_record
	{
		
		private string _CASENO;
		
		private string _uid;
		
		private string _cname;
		
		private System.Nullable<System.DateTime> _SDATE;
		
		private byte _OD_idx;
		
		private string _rid;
		
		private string _l08;
		
		public v_opdorder_not_match_with_lab_record()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CASENO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CASENO
		{
			get
			{
				return this._CASENO;
			}
			set
			{
				if ((this._CASENO != value))
				{
					this._CASENO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", DbType="NVarChar(50)")]
		public string uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this._uid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cname", DbType="NVarChar(50)")]
		public string cname
		{
			get
			{
				return this._cname;
			}
			set
			{
				if ((this._cname != value))
				{
					this._cname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDATE", DbType="Date")]
		public System.Nullable<System.DateTime> SDATE
		{
			get
			{
				return this._SDATE;
			}
			set
			{
				if ((this._SDATE != value))
				{
					this._SDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OD_idx", DbType="TinyInt NOT NULL")]
		public byte OD_idx
		{
			get
			{
				return this._OD_idx;
			}
			set
			{
				if ((this._OD_idx != value))
				{
					this._OD_idx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rid", DbType="NVarChar(50)")]
		public string rid
		{
			get
			{
				return this._rid;
			}
			set
			{
				if ((this._rid != value))
				{
					this._rid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l08", DbType="NVarChar(255)")]
		public string l08
		{
			get
			{
				return this._l08;
			}
			set
			{
				if ((this._l08 != value))
				{
					this._l08 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
